var date = new Date();
console.log(date);
console.log(date.toDateString());
console.log(date.toTimeString());
console.log(date.toLocaleString());
console.log(date.getFullYear());
console.log(date.getTimezoneOffset());
console.log(date.getMonth());
console.log(date.getTime());
console.log(date.getHours());
